Repository Gn0M3Team/Gn0m3Game, pull requests merged in 2025-04, with the labels that each got.

#22 map editor updates
  logs/error.log
  logs/error.log.lck
  src/main/java/com/gnome/gnome/aspects/TransactionalAspect.java
  src/main/java/com/gnome/gnome/editor/controller/EditorPageController.java
  src/main/java/com/gnome/gnome/editor/utils/GenerateGrid.java
  src/main/resources/com/gnome/gnome/pages/editor-view.fxml
Labels: enhancement

#36 styles for map editor
  logs/error.log
  src/main/java/com/gnome/gnome/HelloApplication.java
  src/main/resources/com/gnome/gnome/pages/continueGame.fxml
  src/main/resources/com/gnome/gnome/pages/css/mapEditor.css
  src/main/resources/com/gnome/gnome/pages/editor-view.fxml
  src/main/resources/com/gnome/gnome/pages/fonts/DigitalDisco-Thin.ttf
  src/main/resources/com/gnome/gnome/pages/fonts/DigitalDisco.ttf
Labels: enhancement

#39 changed the error from the previous merge
  logs/error.log
  src/main/java/com/gnome/gnome/HelloController.java
Labels: bug

#51 player session and finalization of page switching
  logs/error.log
  src/main/java/com/gnome/gnome/HelloApplication.java
  src/main/java/com/gnome/gnome/HelloController.java
  src/main/java/com/gnome/gnome/account/controller/AccountController.java
  src/main/java/com/gnome/gnome/account/model/Account.java
  src/main/java/com/gnome/gnome/components/LeaderBoardView.java
  src/main/java/com/gnome/gnome/continueGame/ContinueGameController.java
  src/main/java/com/gnome/gnome/dao/userDAO/UserSession.java
  src/main/java/com/gnome/gnome/editor/controller/EditorPageController.java
  src/main/java/com/gnome/gnome/login/controller/LoginPageController.java
  src/main/java/com/gnome/gnome/loginRegistration/LoginRegistrationController.java
  src/main/java/com/gnome/gnome/loginRegistration/controller/LoginRegistrationController.java
  src/main/java/com/gnome/gnome/newGame/NewGameController.java
  src/main/java/com/gnome/gnome/profile/ProfileController.java
  src/main/java/com/gnome/gnome/registration/controller/RegistretionPageController.java
  src/main/java/com/gnome/gnome/registration/model/Registretion.java
  src/main/java/com/gnome/gnome/setting/SettingController.java
  src/main/java/com/gnome/gnome/settings/SettingController.java
  src/main/java/com/gnome/gnome/shopPopUp/ShopPopUpController.java
  src/main/java/com/gnome/gnome/switcher/controller/SwitcherPageController.java
  src/main/java/com/gnome/gnome/switcher/switcherPage/PageSwitcherInterface.java
  src/main/java/com/gnome/gnome/switcher/switcherPage/SwitchPage.java
  src/main/java/com/gnome/gnome/switcher/switcherPage/component/SceneSwitch.java
  src/main/java/module-info.java
  src/main/resources/com/gnome/gnome/pages/continueGame.fxml
  src/main/resources/com/gnome/gnome/pages/css/main_menu.css
  src/main/resources/com/gnome/gnome/pages/css/new-game.css
  src/main/resources/com/gnome/gnome/pages/css/setting.css
  src/main/resources/com/gnome/gnome/pages/css/shop-pop-up.css
  src/main/resources/com/gnome/gnome/pages/editor-view.fxml
  src/main/resources/com/gnome/gnome/pages/login-registration.fxml
  src/main/resources/com/gnome/gnome/pages/main-menu.fxml
  src/main/resources/com/gnome/gnome/pages/new-game.fxml
  src/main/resources/com/gnome/gnome/pages/profile-page.fxml
  src/main/resources/com/gnome/gnome/pages/setting-view.fxml
  src/main/resources/com/gnome/gnome/pages/setting.fxml
  src/main/resources/com/gnome/gnome/pages/shop-pop-up.fxml
  src/main/resources/com/gnome/gnome/pages/switchingPage/account.fxml
  src/main/resources/com/gnome/gnome/pages/switchingPage/login.fxml
  src/main/resources/com/gnome/gnome/pages/switchingPage/registration.fxml
  src/main/resources/com/gnome/gnome/pages/switchingPage/switcher-page.fxml
Labels: enhancement, good first issue

#56 selection in map editor base on photo
  logs/error.log
  src/main/java/com/gnome/gnome/editor/controller/EditorPageController.java
  src/main/java/com/gnome/gnome/editor/javafxobj/TemplateMapDialog.java
  src/main/java/com/gnome/gnome/editor/utils/BotType.java
  src/main/java/com/gnome/gnome/editor/utils/CategoryGenerator.java
  src/main/resources/com/gnome/gnome/maps/template1.map
  src/main/resources/com/gnome/gnome/maps/template2.map
  src/main/resources/com/gnome/gnome/pages/css/main_menu.css
  src/main/resources/com/gnome/gnome/pages/editor-view.fxml
Labels: enhancement

#58 fix import dependence
  logs/error.log
  src/main/java/com/gnome/gnome/editor/controller/EditorPageController.java
  src/main/resources/com/gnome/gnome/pages/css/login-registration.css
Labels: bug

#62 add new ability to add monster on the map
  src/main/java/com/gnome/gnome/HelloController.java
  src/main/java/com/gnome/gnome/editor/controller/EditorPageController.java
  src/main/java/com/gnome/gnome/editor/utils/BotType.java
  src/main/java/com/gnome/gnome/editor/utils/CategoryGenerator.java
  src/main/java/com/gnome/gnome/editor/utils/GenerateGrid.java
  src/main/java/com/gnome/gnome/editor/utils/TypeOfObjects.java
Labels: enhancement

#76 increase number of different props
  .idea/misc.xml
  src/main/java/com/gnome/gnome/editor/utils/CategoryGenerator.java
  src/main/java/com/gnome/gnome/editor/utils/GridManager.java
  src/main/java/com/gnome/gnome/editor/utils/TypeOfObjects.java
  src/main/resources/com/gnome/gnome/pages/editor-view.fxml
Labels: enhancement

#75 Create following MovementStrategy by astar algorythm.
  src/main/java/com/gnome/gnome/continueGame/ContinueGameController.java
  src/main/java/com/gnome/gnome/monsters/movements/FollowingMovement.java
  src/main/java/com/gnome/gnome/monsters/movements/MovementStrategy.java
  src/main/java/com/gnome/gnome/monsters/movements/OmnidirectionalMovement.java
  src/main/java/com/gnome/gnome/monsters/movements/RandomMovement.java
  src/main/java/com/gnome/gnome/monsters/movements/StraightMovement.java
Labels: enhancement

#79 db load bug fixed + new elements for map
  src/main/java/com/gnome/gnome/continueGame/ContinueGameController.java
  src/main/java/com/gnome/gnome/editor/utils/CategoryGenerator.java
  src/main/java/com/gnome/gnome/editor/utils/GridManager.java
  src/main/java/com/gnome/gnome/editor/utils/TypeOfObjects.java
  src/main/resources/com/gnome/gnome/pages/editor-view.fxml
Labels: enhancement

#81 add delete map button
  logs/error.log
  src/main/java/com/gnome/gnome/dao/MapDAO.java
  src/main/java/com/gnome/gnome/editor/controller/EditorPageController.java
  src/main/java/com/gnome/gnome/models/Map.java
  src/main/resources/com/gnome/gnome/pages/editor-view.fxml
Labels: enhancement

#82 77 fix player movement and attack
  src/main/java/com/gnome/gnome/camera/Camera.java
  src/main/java/com/gnome/gnome/continueGame/ContinueGameController.java
  src/main/java/com/gnome/gnome/newNewGame/NewNewGameController.java
  src/main/java/com/gnome/gnome/player/Player.java
  src/main/java/com/gnome/gnome/switcher/switcherPage/SwitchPage.java
  src/main/java/module-info.java
  src/main/resources/com/gnome/gnome/pages/css/new_game.css
  src/main/resources/com/gnome/gnome/pages/main-new-game-page.fxml
Labels: bug, enhancement

#84 implemented the logic for viewing an account
  .idea/dataSources.xml
  logs/error.log
  src/main/java/com/gnome/gnome/HelloApplication.java
  src/main/java/com/gnome/gnome/HelloController.java
  src/main/java/com/gnome/gnome/components/LeaderBoardView.java
  src/main/java/com/gnome/gnome/dao/userDAO/AuthUserDAO.java
  src/main/java/com/gnome/gnome/dao/userDAO/UserGameStateDAO.java
  src/main/java/com/gnome/gnome/profile/ProfileController.java
  src/main/java/com/gnome/gnome/setting/SettingController.java
  src/main/resources/com/gnome/gnome/pages/css/leaderboard.css
  src/main/resources/com/gnome/gnome/pages/css/new-game.css
  src/main/resources/com/gnome/gnome/pages/css/profile.css
  src/main/resources/com/gnome/gnome/pages/main-menu.fxml
  src/main/resources/com/gnome/gnome/pages/profile-page.fxml
  src/main/resources/com/gnome/gnome/pages/setting.fxml
Labels: enhancement

#94 92 fix full screen for game
  src/main/java/com/gnome/gnome/camera/Camera.java
  src/main/java/com/gnome/gnome/continueGame/ContinueGameController.java
  src/main/java/com/gnome/gnome/editor/utils/TypeOfObjects.java
  src/main/java/com/gnome/gnome/game/GameController.java
  src/main/java/com/gnome/gnome/player/Player.java
  src/main/resources/app.properties
Labels: bug

#93 deleted continueController + cleaned code + db data uploading
  pom.xml
  src/main/java/com/gnome/gnome/MainApplication.java
  src/main/java/com/gnome/gnome/MainController.java
  src/main/java/com/gnome/gnome/camera/Camera.java
  src/main/java/com/gnome/gnome/components/LeaderBoardView.java
  src/main/java/com/gnome/gnome/continueGame/ContinueGameController.java
  src/main/java/com/gnome/gnome/dao/userDAO/UserSession.java
  src/main/java/com/gnome/gnome/game/GameController.java
  src/main/java/com/gnome/gnome/game/MapLoader.java
  src/main/java/com/gnome/gnome/loginRegistration/controller/LoginRegistrationController.java
  src/main/java/com/gnome/gnome/monsters/movements/FollowingMovement.java
  src/main/java/com/gnome/gnome/newGame/NewGameController.java
  src/main/java/com/gnome/gnome/newNewGame/NewNewGameController.java
  src/main/java/com/gnome/gnome/profile/ProfileController.java
  src/main/java/com/gnome/gnome/storyMaps/StoryModeController.java
  src/main/java/com/gnome/gnome/switcher/switcherPage/PageSwitcherInterface.java
  src/main/java/com/gnome/gnome/switcher/switcherPage/SwitchPage.java
  src/main/java/com/gnome/gnome/switcher/switcherPage/component/SceneSwitch.java
  src/main/java/com/gnome/gnome/userState/UserState.java
  src/main/java/module-info.java
  src/main/resources/com/gnome/gnome/pages/css/story_maps.css
  src/main/resources/com/gnome/gnome/pages/main-menu.fxml
  src/main/resources/com/gnome/gnome/pages/main-new-game-page.fxml
  src/main/resources/com/gnome/gnome/pages/story-mode-page.fxml
Labels: enhancement

#97 96 db data processing
  src/main/java/com/gnome/gnome/camera/Camera.java
  src/main/java/com/gnome/gnome/game/GameController.java
  src/main/java/com/gnome/gnome/game/MapLoader.java
  src/main/resources/app.properties
  src/main/resources/com/gnome/gnome/images/default-no-item.png
Labels: enhancement

#104 103 implement table with user statistics data
  src/main/java/com/gnome/gnome/MainController.java
  src/main/java/com/gnome/gnome/camera/Camera.java
  src/main/java/com/gnome/gnome/dao/UserStatisticsDAO.java
  src/main/java/com/gnome/gnome/dao/userDAO/UserGameStateDAO.java
  src/main/java/com/gnome/gnome/game/GameController.java
  src/main/java/com/gnome/gnome/game/MapLoaderService.java
  src/main/java/com/gnome/gnome/game/MapLoaderUIHandler.java
  src/main/java/com/gnome/gnome/loginRegistration/controller/LoginRegistrationController.java
  src/main/java/com/gnome/gnome/models/UserStatistics.java
  src/main/java/com/gnome/gnome/models/user/UserGameState.java
  src/main/java/com/gnome/gnome/newGame/NewGameController.java
  src/main/java/com/gnome/gnome/profile/ProfileController.java
  src/main/java/com/gnome/gnome/storyMaps/StoryModeController.java
  src/main/java/com/gnome/gnome/userState/UserState.java
  src/main/java/com/gnome/gnome/utils/QuadroConsumer.java
  src/main/resources/com/gnome/gnome/pages/css/story_maps.css
Labels: enhancement

#106 102 testing game and add some interesting feature for upgrading our project
  src/main/java/com/gnome/gnome/camera/Camera.java
  src/main/java/com/gnome/gnome/editor/utils/TypeOfObjects.java
  src/main/java/com/gnome/gnome/game/GameController.java
  src/main/java/com/gnome/gnome/game/MapLoaderService.java
  src/main/java/com/gnome/gnome/game/MapLoaderUIHandler.java
  src/main/java/com/gnome/gnome/game/component/Chest.java
  src/main/java/com/gnome/gnome/game/component/Coin.java
  src/main/java/com/gnome/gnome/game/component/ObjectsConstants.java
  src/main/java/com/gnome/gnome/monsters/Monster.java
  src/main/java/com/gnome/gnome/player/Player.java
  src/main/java/com/gnome/gnome/storyMaps/StoryModeController.java
  src/main/resources/com/gnome/gnome/effects/animated_chest.gif
Labels: bug, enhancement

#108 105 profile page update with player statistics
  logs/error.log
  src/main/java/com/gnome/gnome/components/LeaderBoardView.java
  src/main/java/com/gnome/gnome/dao/MapDAO.java
  src/main/java/com/gnome/gnome/dao/UserStatisticsDAO.java
  src/main/java/com/gnome/gnome/dao/userDAO/AuthUserDAO.java
  src/main/java/com/gnome/gnome/editor/controller/EditorPageController.java
  src/main/java/com/gnome/gnome/loginRegistration/service/LoginRegistrationService.java
  src/main/java/com/gnome/gnome/models/Map.java
  src/main/java/com/gnome/gnome/models/UserStatistics.java
  src/main/java/com/gnome/gnome/profile/ProfileController.java
  src/main/java/com/gnome/gnome/userState/UserState.java
  src/main/resources/com/gnome/gnome/images/default-avatar-2.png
  src/main/resources/com/gnome/gnome/images/default-avatar.png
  src/main/resources/com/gnome/gnome/pages/css/profile-delete-user.css
  src/main/resources/com/gnome/gnome/pages/css/profile.css
  src/main/resources/com/gnome/gnome/pages/css/story_maps.css
  src/main/resources/com/gnome/gnome/pages/profile-page.fxml
Labels: enhancement
