Repository Gn0M3Team/Gn0m3Game, pull requests merged in 2025-05, with the labels that each got.

#112 109 update maps functionality
  logs/error.log
  src/main/java/com/gnome/gnome/dao/MapDAO.java
  src/main/java/com/gnome/gnome/editor/controller/EditorPageController.java
  src/main/java/com/gnome/gnome/editor/utils/MapValidator.java
  src/main/java/com/gnome/gnome/profile/ProfileController.java
  src/main/java/com/gnome/gnome/utils/AlertUtil.java
  src/main/java/com/gnome/gnome/utils/CustomPopupUtil.java
  src/main/resources/com/gnome/gnome/pages/css/dialogs/custom-popup-alert.css
  src/main/resources/com/gnome/gnome/pages/editor-view.fxml
  src/main/resources/com/gnome/gnome/pages/profile-page.fxml
Labels: enhancement

#113 107 fix bugs related to menu
  hs_err_pid12430.log
  hs_err_pid13704.log
  src/main/java/com/gnome/gnome/camera/Camera.java
  src/main/java/com/gnome/gnome/editor/utils/TypeOfObjects.java
  src/main/java/com/gnome/gnome/exceptions/ImageNotFoundException.java
  src/main/java/com/gnome/gnome/game/GameController.java
  src/main/java/com/gnome/gnome/game/GameInitializer.java
  src/main/java/com/gnome/gnome/game/GameUIManager.java
  src/main/java/com/gnome/gnome/game/MovementService.java
  src/main/java/com/gnome/gnome/monsters/Monster.java
  src/main/java/com/gnome/gnome/monsters/types/Butterfly.java
  src/main/java/com/gnome/gnome/monsters/types/Demon.java
  src/main/java/com/gnome/gnome/monsters/types/Goblin.java
  src/main/java/com/gnome/gnome/monsters/types/Scorpion.java
  src/main/java/com/gnome/gnome/monsters/types/Skeleton.java
  src/main/java/com/gnome/gnome/monsters/types/missels/Arrow.java
  src/main/java/com/gnome/gnome/player/Player.java
  src/main/java/module-info.java
Labels: bug

#117 Implement shop logic
  logs/error.log
  src/main/java/com/gnome/gnome/MainApplication.java
  src/main/java/com/gnome/gnome/MainController.java
  src/main/java/com/gnome/gnome/exceptions/BalanceException.java
  src/main/java/com/gnome/gnome/shop/controllers/ItemController.java
  src/main/java/com/gnome/gnome/shop/controllers/ShopController.java
  src/main/java/com/gnome/gnome/shop/service/ItemsSelector.java
  src/main/java/com/gnome/gnome/shop/service/ShopItem.java
  src/main/java/com/gnome/gnome/shop/service/ShopService.java
  src/main/java/com/gnome/gnome/shop/utils/ItemCategory.java
  src/main/java/com/gnome/gnome/shopPopUp/ShopPopUpController.java
  src/main/java/com/gnome/gnome/switcher/switcherPage/PageSwitcherInterface.java
  src/main/java/com/gnome/gnome/switcher/switcherPage/SwitchPage.java
  src/main/java/com/gnome/gnome/userState/UserState.java
  src/main/java/module-info.java
  src/main/resources/com/gnome/gnome/pages/css/item-modal.css
  src/main/resources/com/gnome/gnome/pages/css/shop-pop-up.css
  src/main/resources/com/gnome/gnome/pages/css/shop.css
  src/main/resources/com/gnome/gnome/pages/item-modal.fxml
  src/main/resources/com/gnome/gnome/pages/shop-pop-up.fxml
  src/main/resources/com/gnome/gnome/pages/shop.fxml
Labels: enhancement

#121 119 fix game over menu
  src/main/java/com/gnome/gnome/MainApplication.java
  src/main/java/com/gnome/gnome/camera/Camera.java
  src/main/java/com/gnome/gnome/dao/MonsterDAO.java
  src/main/java/com/gnome/gnome/game/GameController.java
  src/main/java/com/gnome/gnome/game/MapLoaderService.java
  src/main/java/com/gnome/gnome/game/MovementService.java
  src/main/java/com/gnome/gnome/models/Monster.java
  src/main/java/com/gnome/gnome/monsters/Monster.java
  src/main/java/com/gnome/gnome/player/Player.java
  src/main/java/com/gnome/gnome/shop/controllers/ShopController.java
Labels: bug

#130 bugs solved + front
  logs/error.log
  src/main/java/com/gnome/gnome/MainApplication.java
  src/main/java/com/gnome/gnome/MainController.java
  src/main/java/com/gnome/gnome/camera/Camera.java
  src/main/java/com/gnome/gnome/components/PlayerHealthBar.java
  src/main/java/com/gnome/gnome/game/GameController.java
  src/main/java/com/gnome/gnome/game/GameUIManager.java
  src/main/java/com/gnome/gnome/setting/SettingController.java
  src/main/java/com/gnome/gnome/userState/UserState.java
  src/main/java/com/gnome/gnome/utils/CustomPopupUtil.java
  src/main/resources/com/gnome/gnome/pages/css/continueGame.css
  src/main/resources/com/gnome/gnome/pages/css/dialogs/custom-popup-alert.css
  src/main/resources/com/gnome/gnome/pages/css/game-ui.css
  src/main/resources/com/gnome/gnome/pages/css/settings.css
  src/main/resources/com/gnome/gnome/pages/editor-view.fxml
  src/main/resources/com/gnome/gnome/pages/login-registration.fxml
  src/main/resources/com/gnome/gnome/pages/main-menu.fxml
  src/main/resources/com/gnome/gnome/pages/setting.fxml
Labels: enhancement

#133 loader updated
  logs/error.log
  src/main/java/com/gnome/gnome/editor/controller/EditorPageController.java
  src/main/java/com/gnome/gnome/editor/utils/GenerateGrid.java
  src/main/java/com/gnome/gnome/game/GameController.java
  src/main/java/com/gnome/gnome/game/MapLoaderUIHandler.java
  src/main/resources/com/gnome/gnome/images/tiles/butterfly.png
  src/main/resources/com/gnome/gnome/images/tiles/demon.png
  src/main/resources/com/gnome/gnome/images/tiles/goblin.png
  src/main/resources/com/gnome/gnome/images/tiles/scorpion.png
  src/main/resources/com/gnome/gnome/pages/css/dialogs/map-loader.css
Labels: enhancement

#139 made a separate login and registration
  src/main/java/com/gnome/gnome/loginRegistration/controller/LoginRegistrationController.java
  src/main/java/com/gnome/gnome/loginRegistration/service/LoginRegistrationService.java
  src/main/resources/com/gnome/gnome/pages/css/login-registration.css
  src/main/resources/com/gnome/gnome/pages/login-registration.fxml
Labels: enhancement, good first issue

#154 inventory page + fxml
  logs/error.log
  src/main/java/com/gnome/gnome/MainApplication.java
  src/main/java/com/gnome/gnome/MainController.java
  src/main/java/com/gnome/gnome/dao/UserStatisticsDAO.java
  src/main/java/com/gnome/gnome/inventory/InventoryController.java
  src/main/java/com/gnome/gnome/models/UserStatistics.java
  src/main/java/com/gnome/gnome/profile/ProfileController.java
  src/main/java/com/gnome/gnome/switcher/switcherPage/PageSwitcherInterface.java
  src/main/java/com/gnome/gnome/switcher/switcherPage/SwitchPage.java
  src/main/java/module-info.java
  src/main/resources/com/gnome/gnome/pages/css/dialogs/inventory-sell-conf.css
  src/main/resources/com/gnome/gnome/pages/css/inventory.css
  src/main/resources/com/gnome/gnome/pages/css/profile.css
  src/main/resources/com/gnome/gnome/pages/inventory-page.fxml
  src/main/resources/com/gnome/gnome/pages/main-menu.fxml
  src/main/resources/com/gnome/gnome/pages/profile-page.fxml
  src/main/resources/english.properties
  src/main/resources/slovak.properties
Labels: enhancement

#158 Fix problem when user loss internet connection, we can't access our a…
  src/main/java/com/gnome/gnome/MainApplication.java
  src/main/java/com/gnome/gnome/db/DatabaseWrapper.java
  src/main/java/com/gnome/gnome/utils/InternetMonitor.java
Labels: bug

#162 fix error internet connection
  src/main/java/com/gnome/gnome/MainApplication.java
  src/main/java/com/gnome/gnome/utils/InternetMonitor.java
Labels: bug

#166 159 fix animations for chest also try to fix problem with 3 level
  src/main/java/com/gnome/gnome/game/GameController.java
  src/main/java/com/gnome/gnome/profile/ProfileController.java
  src/main/java/com/gnome/gnome/utils/InternetMonitor.java
Labels: bug
